---
:test: Bike1D
:active: true
:data_backup: true
:vars: 
  - time
  - vmur
  - vmuf
  - vmurControl
  - vmufControl
:graph:
  - :name: SpeedGraph
    :x_axis: time
    :y_axis:
      - :name: mur
        :color: red
        :legend: vmur
      - :name: muf
        :color: black
        :legend: vmuf
  - :name: ControlInput
    :x_axis: time
    :y_axis:
      - :name: murControl
        :color: red
        :legend: ctrlR
      - :name: mufControl
        :color: black
        :legend: ctrlL